import { CssBaseline } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import theme from '../theme';
import { LayoutWithDrawer } from './components/LayoutWithDrawer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />

        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <LayoutWithDrawer>{children}</LayoutWithDrawer>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
